# Generated by Django 2.2.16 on 2022-08-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220806_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
