# Generated by Django 3.2.15 on 2022-08-09 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220809_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient', verbose_name='Инредиент'),
        ),
    ]
