# Generated by Django 3.2.15 on 2022-08-09 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ingredientamount_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='measurement_unit',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='Ingredient_recipe', through='api.IngredientAmount', to='api.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='api.ingredient', verbose_name='Инредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_ingredients', to='api.recipe', verbose_name='Рецепт'),
        ),
    ]
