# Generated by Django 3.2.15 on 2022-08-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220809_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.CharField(max_length=56, verbose_name='Количество'),
        ),
    ]
