# Generated by Django 2.2.16 on 2022-08-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220809_1857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag_to_Recipe',
            new_name='TagRecipe',
        ),
    ]
